server:
  port: 80

spring:
  application:
    name: 13-cloud-consumer-feign-hystrix-order-80

eureka:
  client:
    register-with-eureka: false #客户端调用不注册进注册中心
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka

#开启hystrix配置
feign:
  hystrix:
    enabled: true
