server:
  port: 8003

################################ datasource ############################################
spring:
  application:
    name: account-serve-center
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource  # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver   # mysql驱动包
    url: jdbc:mysql://localhost:3306/seata_account?characterEncoding=utf-8&useSSL=false
    username: root
    password: admin123
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
################################ mybatis-plus ############################################
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.maizi.domain  # 所有Entity别名类所在包


