server:
  port: 2001

spring:
  application:
    name: seata-order-service
  ################################ datasource ############################################
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource            # 当前数据源操作类型
    driver-class-name: com.mysql.cj.jdbc.Driver   # mysql驱动包
    url: jdbc:mysql://localhost:3306/seata_order?characterEncoding=utf-8&useSSL=false
    username: root
    password: admin123
  #    datasource1:
  #      url: jdbc:mysql://localhost:3306/database01?rewriteBatchedStatements=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
  #      username: root
  #      password: admin
  #    datasource2:
  #      url: jdbc:mysql://localhost:3306/database02?rewriteBatchedStatements=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&serverTimezone=Asia/Shanghai
  #      username: root
  #      password: admin
  cloud:
    ################################ seata ############################################
    alibaba:
      seata:
        #自定义事务组名称需要与seata-server中的对应
        tx-service-group: fsp_tx_group
    ################################ nacos ############################################
    nacos:
      discovery:
        server-addr: localhost:8848



################################ feign ############################################
feign:
  hystrix:
    enabled: false

logging:
  level:
    io:
      seata: info

mybatis:
  mapperLocations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl