server:
  port: 9001

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        server-addr: localhost:1111 #Nginx 负载均衡

management:
  endpoints:
    web:
      exposure:
        include: '*'


